version: '3.4'

services:
  car-service:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
